# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

def common_pods
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'MBProgressHUD'
  pod 'TOCropViewController'
  pod 'NIMSDK_LITE', '9.16.5'
  #矢量动画框架
  pod 'lottie-ios'
  #上拉加载 下拉刷新
  pod 'MJRefresh'
  #RxSwift
  pod 'RxSwift', '~> 6.8.0'
  pod 'RxCocoa', '~> 6.8.0'
  #分页控制
  pod 'JXSegmentedView'
  #多语言
  pod 'Localize-Swift'
  #弹窗
  pod 'SDCAlertView'
end

def ads_pods
  # 穿山甲依赖
  pod 'Ads-CN-Beta','6.7.0.3', :subspecs => ['BUAdSDK', 'CSJMediation']
  pod 'TTSDKFramework', '1.42.3.4-premium', :subspecs => [ 'Player-SR' ]
  pod 'Pangrowth', '5.3.0.0', :subspecs => [ 'media' ]
      
end

target 'huanxi' do
  common_pods
  ads_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
