# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'huanxi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for huanxi
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SnapKit'
#  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'iCarousel'

  
  pod 'NIMSDK_LITE', '9.16.5'

#  
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#      end
#    end
#  end
  
  target 'huanxiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'huanxiUITests' do
    # Pods for testing
  end

end
